# Generated by Django 3.0.7 on 2020-06-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_link', models.CharField(max_length=250)),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to=None)),
                ('featured', models.BooleanField(blank=True, default=False)),
                ('title', models.CharField(max_length=350)),
                ('subtitle', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=150)),
                ('catagory', models.CharField(max_length=550)),
            ],
        ),
    ]
