# Generated by Django 3.0.7 on 2020-07-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_db_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='submitted_articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='blog_db',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
