# Generated by Django 3.0.7 on 2020-07-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200715_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitted_articles',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blog_db',
            name='img_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
