# Generated by Django 3.0.7 on 2020-07-23 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200723_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitted_articles',
            name='viewed',
        ),
    ]
