# Generated by Django 3.0.7 on 2020-07-26 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_submitted_articles_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_db',
            name='read_time',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
